- name: Copying hosts names to all /etc/hosts nodes
  hosts: mapr-hosts
  roles:
    - etc-hosts-copy
  become: true
  become_user: root

- name: Setup MapR repositories
  hosts: mapr-core
  roles:
    - mapr-configure-repository
  become: true
  become_user: root

- name: Apply common configuration to all nodes
  hosts: common
  roles:
    - common-prereq
    - common-selinux
    - {role: common-oraclejdk18, when: jdk == 'oraclejdk18'}
    - {role: common-openjdk18, when: jdk == 'openjdk18'}
    - {role: common-mapruser, when: mapr_create_user == true}
    - common-rpcbind
    - common-ntp
    - common-misc
    - common-sysctl
  become: true
  become_user: root

# used by configure.sh and drill
- name: Setup global vars
  hosts: all
  roles:
    - mapr-configure-vars
    - mapr-configure-vars-hs
- name: Install MapR Core
  hosts: mapr-core
  roles:
    - mapr-core
- name: Install Zookeeper
  hosts: mapr-zookeeper
  roles:
    - mapr-zookeeper
- name: Install CLDB
  hosts: mapr-cldb
  roles:
    - mapr-cldb
- name: Install Gateway
  hosts: mapr-gateway
  roles:
    - mapr-gateway
- name: Install Filesystem, MapReduce2, YARN Node Manager
  hosts: mapr-datanode
  roles:
    - mapr-fileserver
    - mapr-mapreduce2
    - mapr-nodemanager
- name: Install YARN Resource Manager
  hosts: mapr-resourcemanager
  roles:
    - mapr-resourcemanager
- name: Install MySQL
  hosts: ext-mysql
  roles:
    - ext-mysql
- name: Install MCS
  hosts: mapr-mcs
  roles:
    - mapr-mcs
- name: Install NFS
  hosts: mapr-nfs
  roles:
    - mapr-nfs
- name: Configure and start (unsecure)
  hosts: mapr-core
  roles:
   - {role: mapr-configure-unsecure, when: mapr_security == 'none'}
- name: Configure and start (native-security)
  hosts: mapr-core
  roles:
   - {role: mapr-configure-nativesecurity-secure, when: mapr_security == 'maprsasl'}
- name: Configure and start (kerberos)
  hosts: mapr-core
  roles:
   - {role: mapr-configure-kerberos, when: mapr_security == 'kerberos'}
- name: Restarting mapr-zookeeper
  hosts: mapr-zookeeper
  roles:
   - mapr-configure-zookeeper-restart
- name: Restarting mapr-warden
  hosts: mapr-core
  roles:
   - mapr-configure-warden-restart
- name: Install History Server
  hosts: mapr-historyserver
  roles:
    - mapr-historyserver
- name: Install tez
  hosts: mapr-tez
  roles:
    - mapr-tez
- name: Setup Hive Variables
  hosts: all
  roles:
    - mapr-hive-vars
    - {role: mapr-hive-mysql, when: hive_db_type == 'mysql' and hive_db_mysql_create_schema_and_user == true}
- name: Install Hive CLI
  hosts: mapr-hive-cli
  roles:
    - mapr-hive-cli
- name: Install Hive MetaStore
  hosts: mapr-hive-metastore
  roles:
    - mapr-hive-metastore
- name: Install Hive Server 2
  hosts: mapr-hive-server2
  roles:
    - mapr-hive-server2
- name: Install Hive WebHCat
  hosts: mapr-hive-webhcat
  roles:
    - mapr-hive-webhcat
- name: Install HttpFS
  hosts: mapr-httpfs
  roles:
    - mapr-httpfs
- name: Install Spark on YARN
  hosts: mapr-spark-yarn
  roles:
    - mapr-spark-yarn
- name: Install Spark History Server
  hosts: mapr-spark-historyserver
  roles:
    - mapr-spark-historyserver
- name: Setup Hue Vars
  hosts: all
  roles:
    - mapr-hue-vars
    - {role: mapr-hue-mysql, when: hive_db_type == 'mysql' and hue_db_mysql_create_schema_and_user == true}
- name: Install Hue
  hosts: mapr-hue
  roles:
    - mapr-hue
- name: Register roles and restart mapr-warden
  hosts: mapr-core
  roles:
    - mapr-configure-roles
    - mapr-configure-warden-restart
- name: Restarting mapr-warden
  hosts: mapr-core
  roles:
   - mapr-configure-warden-restart
