---
# Install MapR Core components for all machines
- name: Install mapr-core
  vars:
    packages_Suse: ['mapr-compat-suse', 'mapr-core', 'mapr-core-internal', 'mapr-kafka']
    packages_RedHat: ['mapr-core', 'mapr-core-internal', 'mapr-kafka']
    packages_Debian: ['mapr-core', 'mapr-core-internal', 'mapr-kafka']
  package: name={{ item }} state=present
  with_items: "{{ vars['packages_' + ansible_os_family] }}"
- name: Configure core-site.xml
  vars:
    aws_credentials_file: "{{ lookup('env','HOME') }}/.aws/credentials"
    aws_access_key_id: "{{ lookup('ini', 'aws_access_key_id section=default file={{ aws_credentials_file }}')  }}"
    aws_secret_access_key: "{{ lookup('ini', 'aws_secret_access_key section=default file={{ aws_credentials_file }}')  }}"
  template: src=core-site.xml dest=/opt/mapr/hadoop/hadoop-{{ hadoop_version }}/etc/hadoop/core-site.xml
  ignore_errors: True
- name: Configure yarn-site.xml for Unsecure
  template: src=yarn-site.unsecure.xml dest=/opt/mapr/hadoop/hadoop-{{ hadoop_version }}/etc/hadoop/yarn-site.xml
  when: mapr_security == 'none'
# Resuse unsecure template
- name: Configure yarn-site.xml for Native Security
  template: src=yarn-site.unsecure.xml dest=/opt/mapr/hadoop/hadoop-{{ hadoop_version }}/etc/hadoop/yarn-site.xml
  when: mapr_security == 'maprsasl'
- name: Configure yarn-site.xml for Kerberos
  template: src=yarn-site.kerberos.xml dest=/opt/mapr/hadoop/hadoop-{{ hadoop_version }}/etc/hadoop/yarn-site.xml
  when: mapr_security == 'kerberos'

- name: Set MAPR_LOGIN_OPTS in env.sh to hybrid
  lineinfile: dest=/opt/mapr/conf/env.sh regexp="^MAPR_LOGIN_OPTS" line="MAPR_LOGIN_OPTS=\"-Dhadoop.login=hybrid ${MAPR_JAAS_CONFIG_OPTS} ${MAPR_ZOOKEEPER_OPTS}\""
  when: mapr_security == 'kerberos'
