---
# Install Spark on YARN
- name: Install mapr-spark-historyserver
  package: name=mapr-spark-historyserver state=present

# Other actions
- name: Configure.sh -R
  shell: /opt/mapr/server/configure.sh -R
- name: Set owner mapr-system user
  file: path=/opt/mapr/spark owner={{ mapr_user }} group={{ mapr_group }} state=directory recurse=yes